// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
)

type Service struct {
	ID          uuid.UUID
	Name        string
	Description interface{}
}
