// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: services.sql

package db

import (
	"context"
)

const addServices = `-- name: AddServices :many
SELECT id, name, description FROM services limit $1 offset $2
`

type AddServicesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) AddServices(ctx context.Context, arg AddServicesParams) ([]Service, error) {
	rows, err := q.db.Query(ctx, addServices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
